version: '3.0'

services: 


  nginx:
    image: nginx
    ports:
        - "80:80"
    links:
        - phpfpm
    volumes:
        - ./nginx/default:/etc/nginx/conf.d/default.conf
        - ./nginx/packages.conf:/etc/nginx/conf.d/packages.conf

        - ./public:/usr/share/nginx/html

        - ./nginx/logs/nginx-error.log:/var/log/nginx/error.log
        - ./nginx/logs/nginx-access.log:/var/log/nginx/access.log
    network:
      - "netservice"

  phpfpm:
      image: php:7.2-fpm
      ports:
          - "9000:9000"
      volumes:
          - ./public:/usr/share/nginx/html
    network:
      - "netservice"

  mysql:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=changeme
    ports:
      - "3306:3306" 
    volumes:
      - ./db/:/var/lib/mysql
    networks:
      - "netservice"
   deploy:
      placement:
        constraints: [node.role == manager]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - mysql
    ports:
      - 8183:80
    environment:
      PMA_USER: root
      PMA_PASSWORD: admin
      PMA_ARBITRARY: 1
    network:
      - "netservice"

  gitlab:
    image: gitlab/gitlab-ce:latest
    volumes:
        - ./srv/gitlab/config:/etc/gitlab
        - ./srv/gitlab/logs:/var/log/gitlab
        - ./srv/gitlab/data:/var/opt/gitlab
    hostname: git.sudio.co
    network:
      - "netservice"
    ports:
      - "440:443"
      - "8080:8080"
      - "22:22"


network:
  netservice:
volumes:
  data:

#  dockerswarmgui:
#    image: julienbreux/docker-swarm-gui:latest
#    ports:
#      - "8181:8181"

#  gitea:
#    image: gitea/gitea:1.3.2
#    volumes:
#      - ./data:/data
#    ports:
#      - "3000:3000"
#      - "22:22"
#    depends_on:
#      - mysql
#    restart: always





